"""Domain models for OMNIA Executive Review Engine (COO Strategy Engine)."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4


def utc_now() -> datetime:
    return datetime.now(tz=UTC)


class ReviewType(StrEnum):
    DAILY_BRIEF = "DAILY_BRIEF"
    MORNING_BRIEF = "MORNING_BRIEF"
    EVENING_WRAPUP = "EVENING_WRAPUP"
    WEEKLY_EXECUTIVE = "WEEKLY_EXECUTIVE"
    MONTHLY_BUSINESS = "MONTHLY_BUSINESS"
    QUARTERLY_STRATEGY = "QUARTERLY_STRATEGY"
    ANNUAL_REFLECTION = "ANNUAL_REFLECTION"
    MILESTONE_REVIEW = "MILESTONE_REVIEW"


class BusinessImpact(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    POSTPONED = "POSTPONED"
    DELEGATED = "DELEGATED"
    DISMISSED = "DISMISSED"


@dataclass(slots=True)
class RecommendationItem:
    """A grounded strategic recommendation produced by the Executive Review Engine."""

    id: str = field(default_factory=lambda: f"rec-{uuid4().hex[:8]}")
    observation: str = ""
    supporting_memories: list[str] = field(default_factory=list)
    historical_comparison: str = ""
    business_impact: BusinessImpact = BusinessImpact.HIGH
    confidence_score: float = 0.94
    recommended_action: str = ""
    linked_goal_id: str | None = None
    status: RecommendationStatus = RecommendationStatus.PENDING

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "observation": self.observation,
            "supporting_memories": self.supporting_memories,
            "historical_comparison": self.historical_comparison,
            "business_impact": self.business_impact.value,
            "confidence_score": self.confidence_score,
            "recommended_action": self.recommended_action,
            "linked_goal_id": self.linked_goal_id,
            "status": self.status.value,
        }


@dataclass(slots=True)
class ExecutiveReflection:
    """SWOT matrix and reflections generated by the Executive Review Engine."""

    wins: list[str] = field(default_factory=list)
    mistakes: list[str] = field(default_factory=list)
    opportunities: list[str] = field(default_factory=list)
    threats: list[str] = field(default_factory=list)
    lessons_learned: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "wins": self.wins,
            "mistakes": self.mistakes,
            "opportunities": self.opportunities,
            "threats": self.threats,
            "lessons_learned": self.lessons_learned,
        }


@dataclass(slots=True)
class ExecutiveReview:
    """An immutable COO Executive Review grounded in persistent memory."""

    id: UUID = field(default_factory=uuid4)
    creator_id: str = ""
    created_at: datetime = field(default_factory=utc_now)
    review_type: ReviewType = ReviewType.WEEKLY_EXECUTIVE
    title: str = ""
    summary: str = ""
    recommendations: list[RecommendationItem] = field(default_factory=list)
    reflections: ExecutiveReflection = field(default_factory=ExecutiveReflection)
    goal_progress: dict[str, float] = field(default_factory=dict)
    patterns_detected: list[str] = field(default_factory=list)
    is_immutable: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": str(self.id),
            "creator_id": self.creator_id,
            "created_at": self.created_at.isoformat(),
            "review_type": self.review_type.value,
            "title": self.title,
            "summary": self.summary,
            "recommendations": [rec.to_dict() for rec in self.recommendations],
            "reflections": self.reflections.to_dict(),
            "goal_progress": self.goal_progress,
            "patterns_detected": self.patterns_detected,
            "is_immutable": self.is_immutable,
        }
